version: 2.1

orbs:
  codecov: codecov/codecov@1.2.0

references:
  workspace_root: &workspace_root
    /home/circleci/bezier-react

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
  resource_class: large
  working_directory: *workspace_root

  docker:
    - image: node:16.2.0

filter_only_tagged: &filter_only_tagged
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - bezier-react-dependencies-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: bezier-react-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run lint

  typecheck:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run typecheck

  jest:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run jest
      - codecov/upload:
          file: './coverage/clover.xml'
          token: $CODECOV_TOKEN

  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run build

  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run semantic-release

workflows:
  version: 2
  install_n_test:
    jobs:
      - install
      - lint:
          requires:
            - install
          filters:
            branches:
              ignore:
                - master
      - typecheck:
          requires:
            - install
          filters:
            branches:
              ignore:
                - master
      - jest:
          requires:
            - install

  release:
    jobs:
      - install:
          filters:
            branches:
              - master
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - jest:
          requires:
            - install
      - build:
          requires:
            - lint
            - typecheck
            - jest
      - release:
          requires:
            - build
