version: 2.1

orbs:
  codecov: codecov/codecov@1.2.0

references:
  workspace_root: &workspace_root
    /home/circleci/bezier-react

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
  resource_class: large
  working_directory: *workspace_root

  docker:
    - image: node:16.2.0

filter_only_tagged: &filter_only_tagged
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - bezier-react-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - .yarn/cache
            - .yarn/unplugged
          key: bezier-react-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn lint

  typecheck:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn typecheck

  jest:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn workspace @channel.io/bezier-react jest
      - codecov/upload:
          file: './packages/bezier-react/coverage/lcov.info'
          token: $CODECOV_TOKEN

  chromatic-deployment:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn workspace @channel.io/bezier-react chromatic --exit-zero-on-changes --skip 'dependabot/**'

workflows:
  version: 2
  Test & Deploy Chromatic:
    jobs:
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - jest:
          requires:
            - install
      - chromatic-deployment:
          requires:
            - lint
            - typecheck
