name: "기능 추가 및 개선"
description: "새로운 기능(컴포넌트 등) 추가 혹은 기존 기능의 개선 제안"
labels: ["need triage"]
body:
  - type: "markdown"
    attributes:
      value: |
        이슈를 작성해주셔서 감사드립니다.
        작성하시기 이전에, 같은 이슈가 있는지 먼저 검색해주세요!
  - type: "textarea"
    id: "description"
    attributes:
      label: "요약"
      description: "제안하려는 내용에 대해 1~2줄 이내로 요약해주세요."
    validations:
      required: true
  - type: "textarea"
    id: "reason"
    attributes:
      label: "제안 이유"
      description: |
        해당 기능이 추가/개선되어야 하는 이유에 대해 자세히 설명해주세요.
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "개선 방안"
      description: |
        문제를 개선할 수 있는 구체적인 방안에 대해 알려주세요. 코드 조각 등을 더해주시면 더욱 좋습니다.
    validations:
      required: true
  - type: "textarea"
    id: "reference"
    attributes:
      label: "레퍼런스"
      description: |
        참고할만한 자료가 있다면 첨부해주세요.